channels:
    - pytorch
    - nvidia
    - conda-forge
name:
    FlashMu
dependencies:
    - einops
    - jupyter
    - pytorch >=2.0
    - pytorch-cuda>=11.5
    - torchvision
    - tqdm
    - tensorly
    - numpy
    - matplotlib 
    - wandb
    - pip
    - pip:
        - patchify

    
